apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pod-getter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - create
