apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-get-binding
  namespace: training
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-getter
subjects:
- kind: ServiceAccount
  name: tester
  namespace: training
