apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: hello
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: hello
    spec:
      template: # pod template
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: busybox
            name: hello
            command:
            - /bin/sh
            - -c
            - echo "$(date)"
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
  suspend: true
  concurrencyPolicy: Forbid
status: {}
