apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: hello
        command:
        - /bin/sh
        - -c
        # - cat hello/hello.txt
        - echo "hello world $(date)"
        resources: {}
      restartPolicy: Never
  ttlSecondsAfterFinished: 10
  backoffLimit: 3
status: {}
