apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  nodeSelector:
    tolerate: "true"
  # nodeName: gke-project-x-dev-v2-pool-3-7eed7dc1-ul6y
  affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm: 
         labelSelector:
           matchLabels:
             app: nginx
      
  containers:
  - image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: app
    value: java
    operator: Equal
    effect: NoSchedule
status: {}
