apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox:1.27
        name: busybox
        command:
        - /bin/sh
        - -c
        - sleep 3600
        resources: {}
        volumeMounts:
        - name: cred-vol # file mount
          mountPath: /creds/password.txt
          subPath: pass
        - name: secret-vol # dir mount
          mountPath: /secrets
      volumes:
      - name: cred-vol
        configMap: 
          name: db-creds
      - name: secret-vol
        secret:
          secretName: db-creds-secret
status: {}
