apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      initContainers:
      - image: busybox:1.27
        name: busybox-init
        command:
        - /bin/sh
        - -c
        - touch /data/date.txt
        resources: {}
        volumeMounts:
        - name: data-vol
          mountPath: /data
      containers:
      - image: busybox:1.27
        name: busybox
        command:
        - /bin/sh
        - -c
        - cat /data/date.txt && sleep 3600;
        resources: {}
        volumeMounts:
        - name: data-vol
          mountPath: /data
      volumes:
      - name: data-vol
        emptyDir: {}
status: {}
