apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: training
spec:
  storageClassName: standard # Empty string must be explicitly set otherwise default StorageClass will be set
  # volumeName: test-pv
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce